all: serveur1 serveur2 serveur3
	clear

serveur1: serveur1.c
	gcc serveur1.c -o serveur1

serveur2: serveur2.c
	gcc serveur2.c -o serveur2

serveur3: serveur3.c
	gcc serveur3.c -o serveur3

clean:
	rm -rf serveur1 serveur2 serveur3 copy_*
	clear

